### ISSUE TITLE
Special form for eswiki possible?

### ISSUE THREAD

**Issue by MarcoAurelioWM** [Steinsplitter/uv#8]
Meow! Wondering if we could have https://tools.wmflabs.org/steinsplitter/uv/index.php?specialform=dewiki for eswiki. Too many malformed requests by new users.

The template we use is:

```
{{subst:renombrar usuario
| 1 = current username
| 2 = requested username
| 3 = reasons for the change
}}
```
Maybe we could also simplify the template to make it automatically add the requesting username.

Regards.

**Comment by Steinsplitter** [comment]
Okay, i need to know the target page and the following text translated (you may change it) to es:
"Change username"
"Make sure you're logged in with your current user name.
Please replace "reasons for the change" You should leave a hint or justification."
"Preview & Save"

**Comment by MarcoAurelioWM** [comment]
> Okay, i need to know the target page and the following text translated (you may change it) to es:
> "Change username"

Cambiar el nombre de usuario

> "Make sure you're logged in with your current user name.

Por favor verifica que has iniciado sesión con tu cuenta.

> Please replace "reasons for the change" You should leave a hint or justification."

Por favor reemplaza "razones para el cambio" con una justificación.

> "Preview & Save"

Previsualizar y guardar

However please wait as I'm trying to update our rename template to use less code.

**Comment by MarcoAurelioWM** [comment]
With regards to the template update, well, I've not really had time to look at it so maybe we can do it with the template we have now, should you think that's okay of course. Meow-gards 😄.

**Comment by Steinsplitter** [comment]
https://tools.wmflabs.org/steinsplitter/uv/index.php?&lang=es&specialform=eswiki

**Comment by MarcoAurelioWM** [comment]
It seems there's a problem with the form, as it duplicates the "3=" parameter of the template. See for example https://tools.wmflabs.org/steinsplitter/uv/index.php?specialform=eswiki&username=MarcoAurelio+%28test+3%29&lang=en

Which is weird as I saw the code did indeed had the "2=" parameter correctly coded.

**Comment by Steinsplitter** [comment]
@MarcoAurelioWM Synchronized. Should work now.
